name: Build JOSS PDF

on:
  push:
    branches: [ main ]
    paths:
      - "paper/**"
  pull_request:
    paths:
      - "paper/**"
  workflow_dispatch: {}

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        # Use master (stable); v2 tag isn't available
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # Your paper is in paper/paper.md
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # Matches the output path from the build step
          path: paper/paper.pdf
